### ISSUE TITLE
Consider using `zopfli`'s new streaming encoder feature

### ISSUE THREAD

**Issue by AlexTMjugador** [kornelski/cargo-deb#100]
I've just noticed that `cargo-deb` stopped using Zopfli [in this commit](https://github.com/kornelski/cargo-deb/commit/237a6de1ff436115d7893b693d626e829c2432db) because its API did not properly support streaming compression at the time. However, Zopfli 0.7.4 was released a little while ago with [such support](https://docs.rs/zopfli/0.7.4/zopfli/struct.DeflateEncoder.html). If that limitation was the only reason to stop using Zopfli, you might want to give the new version a try! :smile:

**Comment by kornelski** [comment]
Zopfli is super useful in places where gzip has to be used, like PNG. However, apt has supported xz for a long time now, and xz is a pareto improvement over gzip in speed and compression. Therefore, for cargo-deb I consider gzip support only a low-priority fallback for a small and decreasing number of very old Debian installs.

**Comment by AlexTMjugador** [comment]
That makes sense, thanks for the clarification! I wouldn't mind cobbling together a PR to reintroduce Zopfli when I have time, but feel free to close this issue if you feel Zopfli is no longer in scope for the project.

**Comment by kornelski** [comment]
Yes, I'm happy to accept a PR for this.

**Comment by AlexTMjugador** [comment]
I had some time to ponder this idea and realized that to implement it well I would need to extend the `zopfli` crate API with a writer that outputs data in Gzip format, since wrapping a DEFLATE stream in a Gzip container is a responsibility that should not belong to this crate. After that, I will consider visiting this enhancement again :slightly_smiling_face:

**Comment by AlexTMjugador** [comment]
I have just realized this issue was solved eons ago with PR #112 :joy:

Closing this, all's good!
