### ISSUE TITLE
cargo-deb looks up README.md in wrong dir when using workspace

### ISSUE THREAD

**Issue by pkolaczk** [kornelski/cargo-deb#101]
I have a multi-crate project with the following structure:

```
project_root/crate1/README.md
project_root/crate1/Cargo.toml   // with readme = "README.md"
project_root/crate1/src 
project_root/Cargo.toml                // workspace definition
```

Note there is no README in the project root.

Then I try to build it with:
`cargo deb -p crate1`

```
cargo-deb: unable to read extended description from file: README.md
  because: No such file or directory (os error 2)
```

Creating a symbolic link at the root of the project solves this, which means cargo-deb looks for a top-level README.md, instead of the one associated with the crate selected with `-p`.

**Comment by orhun** [comment]
Related #62
