### ISSUE TITLE
Error "malformed-deb-archive newer compressed control.tar.xz" from Lintian on Ubuntu Xenial with cargo-deb > 1.28.0.

### ISSUE THREAD

**Issue by ximon18** [kornelski/cargo-deb#12]
See: https://github.com/NLnetLabs/krill/runs/4803140070?check_suite_focus=true#step:13:28

This used to work with cargo-deb 1.28.0.

I tried using `--fast` to disable XZ compression but that didn't help.

What [did help](https://github.com/NLnetLabs/krill/runs/4803396836?check_suite_focus=true) was compiling with `--no-default-features` to disable the `lzma` feature.

As there are no release notes that I'm aware of for cargo-deb I tried looking through the [diff of tag 1.34.2 to tag 1.28.0](https://github.com/kornelski/cargo-deb/compare/v1.28.0...v1.34.2) and I see a couple of references to LZMA and XZ but I haven't however tried divide and conquer to find out exactly which release since 1.28.0 introduced the problem.

However with the default features disabled `cargo-deb` now takes almost twice as long, roughly 15 minutes instead of 8 minutes for my build on GH Actions.

**Comment by kornelski** [comment]
I've added `--system-xz` switch that replaces our xz2 library with xz command-line. Does this help?

**Comment by ximon18** [comment]
Thanks @kornelski, I'm not working today, I'll test it as soon as I can and get back to you.

**Comment by ximon18** [comment]
Hi @kornelski,

Unfortunately that doesn't seem to help. I updated our GitHub Actions workflow to [install cargo-deb 1.35.0](https://github.com/NLnetLabs/krill/runs/4919870847?check_suite_focus=true#step:10:15) and to [use the `--system-xz` argument](https://github.com/NLnetLabs/krill/runs/4919870847?check_suite_focus=true#step:12:145) and Lintian still [reports the error](https://github.com/NLnetLabs/krill/runs/4919870847?check_suite_focus=true#step:13:28) when running on Ubuntu Xenial.

Ximon

**Comment by kornelski** [comment]
Good, at least it's not caused by the compression library :)

**Comment by ximon18** [comment]
With 1.34.2 I can compile without `lzma` support AND the Lintian checks **pass** on Xenial.

With 1.36.0 I can compile without `lzma` support but the resulting package the Lintian checks **fail** on Xenial.

With >1.36.0 I can't compile without default features (i.e. without `lzma` support) (due to #43) and so the Lintian checks **fail** on Xenial.

I haven't tested >1.34.2 && < 1.36.0.

**Comment by ximon18** [comment]
> With >1.36.0 I can't compile without default features (i.e. without lzma support) (due to https://github.com/kornelski/cargo-deb/issues/43) and so the Lintian checks fail on Xenial.

The compilation issue was resolved in the 1.38.3 release with the fix of https://github.com/kornelski/cargo-deb/issues/43, but then I'm left with the issue that compiling without default features no longer solves the `malformed-deb-archive` error reported by Lintian on Xenial, i.e. I have the situation now that:

* With 1.34.2 I can compile without lzma support AND the Lintian checks pass on Xenial.
* With 1.36.0+ I can compile without lzma support but the resulting package the Lintian checks fail on Xenial.

E.g. see [this failure](https://github.com/NLnetLabs/routinator/runs/7837800231?check_suite_focus=true#step:15:67) on Xenial when using cargo-deb 1.38.3 which [succeeds](https://github.com/NLnetLabs/routinator/runs/7836455521?check_suite_focus=true#step:15:60) when using cargo-deb 1.34.2.

**Comment by ximon18** [comment]
I don't know. What I do know is that disabling the `lzma` feature makes it work up until cargo-deb 1.34.2 but not later, and when I tried `--system-xz` a while ago (see above) that had no effect.

**Comment by kornelski** [comment]
I've googled, and there are plenty of bugs about Ubuntu not supporting LZMA in 16 and 18. So it seems the problem isn't in the lzma compressor, but the fact that an Ubuntu from 3 LTSes ego can't support dpkg format from the future.

**Comment by ximon18** [comment]
So, I'm confused. Disabling the `lzma` feature used to solve the problem. Was it then the case that that actually disabled something else than, or as well as, LZMA support, and this other thing is where the problem arises?

**Comment by kornelski** [comment]
The Cargo feature disables built-in LZMA support, but in the meantime cargo-deb got a fallback to `xz` command, so it always supports LZMA if the host operating system is able to compress LZMA.

**Comment by ximon18** [comment]
@kornelski: I tried using commit ec4e003 and that [worked](https://github.com/NLnetLabs/routinator/runs/7847075372?check_suite_focus=true#step:15:60)!

**Comment by ximon18** [comment]
@kornelski: Will you make a release containing the ec4e003 fix?
