### ISSUE TITLE
lintian: unknown-field Vcs-Git Vcs-Browser

### ISSUE THREAD

**Issue by dcampbell24** [kornelski/cargo-deb#120]
When I make a package then run lintian on it I get the warnings of:
```
W: unknown-field Vcs-Browser
W: unknown-field Vcs-Git
```

**Comment by kornelski** [comment]
These fields are defined here:

https://www.debian.org/doc/manuals/developers-reference/best-pkging-practices.html#vcs-browser

**Comment by dcampbell24** [comment]
I am confused. Then why is lintian complaining about them? My version is Lintian v2.116.3.

**Comment by artob** [comment]
This is a bit peculiar; if you google for the warning, the only two results are this exact GitHub issue:

https://www.google.com/search?q=lintian+%22W%3A+unknown-field+Vcs-Git%22

<img width="758" alt="Screenshot 2024-10-17 at 1 52 24 PM" src="https://github.com/user-attachments/assets/e9081e07-1d2c-4380-9cfd-c74c1a402a7c">

This would seem to imply that `cargo-deb` is doing _something_ unorthodox here.

**Comment by dcampbell24** [comment]
According to [this](https://www.debian.org/doc/debian-policy/ch-controlfields.html#debian-binary-package-control-files-debian-control) those fields are only part of the source control file not the binary control file.

**Comment by dcampbell24** [comment]
This was merged, closing.
