### ISSUE TITLE
asset paths don't work properly with "--profile"

### ISSUE THREAD

**Issue by TheButlah** [kornelski/cargo-deb#125]
I have a script which creates .debs in either the release profile or a custom "artifact" profile. I tried to specify the location to install the binary in the .deb using the `assets` option. But if I hard-code `target/release/...` in, this breaks on the custom "artifact" profile.

Is there some way to use $PROFILE or something similar in the asset paths?

> To avoid x/y problem: My real problem is that I want to have cargo deb put its binaries in /usr/local/bin instead of /usr/bin. Using the "asset" feature of cargo-deb is I think the only way to do this.

**Comment by kornelski** [comment]
We automatically rewrite target/release to be whatever profile you have.
