### ISSUE TITLE
file modes in top-level ar archive don't match dpkg

### ISSUE THREAD

**Issue by programmerjake** [kornelski/cargo-deb#126]
first bytes in a `.deb` created by dpkg:
```
!<arch>
debian-binary   1611345884  0     0     100644  4         `
2.0
control.tar.xz  1611345884  0     0     100644  10384     `
```

first bytes in a `.deb` created by cargo-deb:
```
!<arch>
debian-binary   1712732414  0     0     644     4         `
2.0
control.tar.gz  1712732414  0     0     644     1435      `
```

notice how the dpkg version has mode `100644`, where the initial `10` indicates that they're files:
https://unix.stackexchange.com/questions/450480/file-permission-with-six-octal-digits-in-git-what-does-it-mean/450488#450488

I encountered this while trying to figure out why `file-roller` couldn't extract the `control.tar.gz` or `data.tar.gz` files...

**Comment by kornelski** [comment]
Please make a PR with a fix.
