### ISSUE TITLE
Switch Digest Signing over to sha256 from md5

### ISSUE THREAD

**Issue by RocketJas** [kornelski/cargo-deb#128]
As the MD5 hash function is considered cryptographically broken, I have switched over the signing to use sha256. I have made this change to a fork and I was wondering if this was appropriate to upstream. https://github.com/RocketJas/cargo-deb/pull/1

**Comment by kornelski** [comment]
Thanks for the suggestion. I've implemented it without OpenSSL, which is a heavy dependency.

**Comment by RocketJas** [comment]
Thank you for fixing this so quickly.
