### ISSUE TITLE
Avoid including copyright information

### ISSUE THREAD

**Issue by martingms** [kornelski/cargo-deb#131]
Hello, and thank you very much for this great utility!

I'm using cargo-deb to build internal debs for distribution within my company, and it mostly fits the bill perfectly.
I do however wish (or perhaps I've missed it?) there was a way to not include copyright information in `/usr/share/doc/..`.
All our debs are for internal use only, so the copyright information is not useful. Having to put a bogus `license = "UNLICENSED"` is not much of an issue, but I'd prefer to avoid the noise, both in `Cargo.toml` and in the `/usr/share/doc/..` tree.

**Comment by kornelski** [comment]
At minimum you only need the `authors` property, which is also used for the `Maintainer` metadata. The `copyright` file is about 250 bytes large, so I don't think it's a big deal.

**Comment by martingms** [comment]
Fair enough!
