### ISSUE TITLE
Allow a cargo sub sub command for --cargo-build (cargo auditable build)

### ISSUE THREAD

**Issue by kpcyrd** [kornelski/cargo-deb#134]
Hello!

I'm trying to use cargo-deb and [cargo-auditable](https://github.com/rust-secure-code/cargo-auditable) together, I noticed `cargo deb` has an option to replace the `build` subcommand with something else so I tried `auditable build` but it seems this is taken as an opaque string (actually looking for a `/usr/bin/cargo-auditable build` binary).

The error looks like this:
```
% cargo deb --cargo-build 'auditable build'
error: no such command: `auditable build`

	View all installed commands with `cargo --list`
	Find a package to install `auditable build` with `cargo search cargo-auditable build`
cargo-deb: build failed
```

I could probably work around this by creating a `cargo-auditable-build` dummy subcommand that calls `cargo auditable build` for me, passing along all arguments:

```sh
#!/bin/sh
shift
cargo auditable build "$@"
```

I think legitimate cargo subcommands are very unlikely to contain spaces, so splitting by space seems fairly safe, but alternatively there could be a `--auditable` flag that internally configures `["auditable", "build"]` without changing anything else about existing `--cargo-build` behavior.

This would allow using `cargo audit bin /usr/bin/...` on files that have been installed with cargo-deb.

Thanks!

**Comment by kornelski** [comment]
This will probably conflict with stripping too, so `--no-strip`.

**Comment by kpcyrd** [comment]
Thanks for the hint!

I've checked in regards to `--no-strip` and the dependency data is stored in a `.dep-v0` section that is left untouched by strip.

**Comment by rjzak** [comment]
I also noticed that Cargo Auditable and Deb don't play nicely together. It seems off to say that the solution is to not have one of them build the binary. But I understand the conflict, both try to build the binary.
