### ISSUE TITLE
Using cargo deb with --locked

### ISSUE THREAD

**Issue by kpcyrd** [kornelski/cargo-deb#136]
I've tried using this command:

```
cargo deb --cargo-build 'auditable build --locked' --deb-version "${DEB_VERSION}" --target aarch64-unknown-linux-musl
```

But noticed this works even if the Cargo.lock file is outdated. After this command completes the `Cargo.lock` file is updated to satisfy the `Cargo.toml` file, this likely happens before `cargo deb` invokes `cargo build`, that's why `cargo build --locked` would not report an error and instead silently use the generated `Cargo.lock`.

This is more of an observation, from what I read in other issues the correct usage for my use-case would be:

```
cargo auditable build --verbose --release --locked --target aarch64-unknown-linux-musl
cargo deb --no-build --deb-version "${DEB_VERSION}" --target aarch64-unknown-linux-musl
```

Leaving this as a note anyway in case it's of interest. :)

(Also thank you very much for the 2.5.0 release!)

**Comment by kornelski** [comment]
` --cargo-build 'auditable build --locked' `

this is not a name of a build command. The `--locked` there is a horrible hack that was never meant to be supported, and is not going to work.

`cargo deb` discovers packages based on `cargo metadata`, not `cargo build`, so your build command is way too late to prevent lockfile from being changed.

**Comment by kpcyrd** [comment]
I do agree this is quite the unfortunate hack.

The call to `cargo metadata` is likely rewriting the `Cargo.lock`, it could be called as `cargo metadata --locked`, which would always require Cargo.toml/Cargo.lock to be in-sync, or `cargo deb` could itself have a `--locked` option which passes this flag conditionally (or this is left as-is and `cargo deb --no-build` is the way to go).

**Comment by kornelski** [comment]
I've added support for `--locked` cargo deb arg.
