### ISSUE TITLE
Keep a Changelog .com?

### ISSUE THREAD

**Issue by dcampbell24** [kornelski/cargo-deb#147]
Maybe you should follow https://keepachangelog.com/en/1.0.0/ because it is a standard and it would suggest making your changelog correct markdown. Currently, you have some style errors like more than one top level item (`#`) and indented lists.

**Comment by orhun** [comment]
Additionally, if you ever want to automatically generate the changelog, you can check out [`git-cliff`](https://git-cliff.org/) 🐻 

- example config: https://github.com/orhun/git-cliff/blob/main/examples/github.toml
- example output: https://github.com/orhun/git-cliff/blob/main/CHANGELOG.md

**Comment by kornelski** [comment]
Sorry, I don't like the git-cliff commit message style. Changelog is a chore for me that I don't like, and keep forgetting about it. Automated changelog won't be smarter than what commits say, so I encourage you to check the commit history.
