### ISSUE TITLE
Improve error "cargo-deb: missing chmod (third array entry) for asset in Cargo.toml"

### ISSUE THREAD

**Issue by brocaar** [kornelski/cargo-deb#23]
As `assets` is an array of arrays, it was not directly clear to me to which entry it was referring to.

I had an error in the fourth entry of `assets` and thought initially the error message was wrong and should have been "fourth array entry". Then I noticed it was because the third entry of the fourth asset was missing. Maybe it should mention the index of the asset too?

**Comment by dcampbell24** [comment]
It currently writes out the file name and it quits on the first error. I think this is ok. Once you fix the first error the second will appear.
