### ISSUE TITLE
Changelog filename for native package

### ISSUE THREAD

**Issue by paguardiolle** [kornelski/cargo-deb#25]
Thanks for your great job. Cargo-deb is very usefull.

However we still have an issue regarding native packages and their changelog name.

If we refer to debian policy (https://www.debian.org/doc/debian-policy/ch-docs.html#s-changelogs)
"Packages that are not Debian-native [...] with the name changelog.Debian.gz"

However it seems that "native package" (aka package related to Debian distro only) must have a filename like "/package/changelog.gz". 

https://www.debian.org/doc/manuals/developers-reference/pkgs.en.html explains:

"This file will be installed in /usr/share/doc/package/changelog.Debian.gz, or /usr/share/doc/package/changelog.gz for native packages."

Can you please add a flag and/or an option to choice bw "changelog.Debian.gz" and "changelog.gz" ?

Many thanks.

**Comment by kornelski** [comment]
I think we're currently generating `changelog.Debian.gz`, which is correct for "non-native" packages. 

I don't plan to support "native" packages, because Debian has many complex requirements for its native packages that a simple crate like this can't easily satisfy. For "proper" Debian packages see [`debcargo`](//lib.rs/debcargo) crate.

**Comment by paguardiolle** [comment]
Ok. Thanks for your answer.

However when a try to package a "hello world" Rust app, my package is still recognized as a native by lintian ? is there sthing I'm missing ?

**Comment by kornelski** [comment]
For Debian "native" means "official". The native packages are the ones shipped by the Debian project, not you (unless you're an official Debian maintainer working for the Debian project).
