### ISSUE TITLE
Running on x86_64 arch always produces *_amd64.deb

### ISSUE THREAD

**Issue by tmarkovski** [kornelski/cargo-deb#3]
First of all, thanks for this great tool! I'm running into an issue - I'm trying to create a package on an x86_64 arch, but the output is always `_amd64.deb` suffixed. I run this in a docker container:

```
root@a3ce369d8454:~/okapi/native# uname -a
Linux a3ce369d8454 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64 GNU/Linux
root@a3ce369d8454:~/okapi/native# arch
x86_64
```

Even running `cargo deb --target=x86_64-unknown-linux-gnu` has the same results. Not an expert on DEB packaging, so I may be missing something here. Any help would be appreciated.

**Comment by kornelski** [comment]
This is working as expected.

64-bit extensions to x86 (IA32) have been invented by AMD, not Intel. Debian uses a technically-correct name for the platform.

**Comment by tmarkovski** [comment]
Thanks @kornelski . I associated arm64 with amd64 for some reason. Cheers.
