### ISSUE TITLE
cargo deb all

### ISSUE THREAD

**Issue by mchodzikiewicz** [kornelski/cargo-deb#31]
Currently `cargo-deb` can build .deb package for a specific binary in a workspace (`-p`), it would be nice to have `cargo-deb` option to build all packages that has deb metadata

**Comment by kornelski** [comment]
I'm not sure if I want to support this. Command-line switches have package-specific meaning, so the next ask will be to support them, and to build all except one, and so on.

Running cargo deb multiple times is not hard.
