### ISSUE TITLE
Why is warning: This command is for Linux only, and will not make sense when run on other systems

### ISSUE THREAD

**Issue by John15321** [kornelski/cargo-deb#33]
Why is this cargo plugin only supposed to work on Linux? I am not familiar with how the Debian packaging system works, but cant it be made cross-platform? Ofc I mean being able to generate a Debian package on any platform to be clear.

Is there even a way to make that happen? If so I would be happy to help

```bash
warning: This command is for Linux only, and will not make sense when run on other systems
```

**Comment by John15321** [comment]
Also I cannot seem to find information about it in the readme (although I just might be blind), so it should be added

**Comment by kornelski** [comment]
You got this error message, because you've created a package without cross-compilation, so your package theoretically works on your non-Linux system, but is incompatible with Linux.

**Comment by John15321** [comment]
> You got this error message, because you've created a package without cross-compilation, so your package theoretically works on your non-Linux system, but is incompatible with Linux.

That makes sense finally, 🙏😅
