### ISSUE TITLE
--profile with does not effect `--no-build`

### ISSUE THREAD

**Issue by Licenser** [kornelski/cargo-deb#34]
when specifying `--profile debug` and `--no-build` cargo deb still looks in `target/release`

```
❯ cargo deb --verbose --no-build --no-strip --target x86_64-unknown-linux-gnu --output /home/heinz/tremor-runtime/packaging/out --deb-version 0.12.2 --profile debug
cargo-deb: Asset file path does not match any files: /home/heinz/tremor-runtime/target/release/tremor
```

**Comment by kornelski** [comment]
This tool is only for making releases, I don't plan to support anything other than target/release.

If you want to make a release with debug information then the correct way is to specify debug=true in a release profile.

**Comment by kornelski** [comment]
And target/debug is a bit confused in Cargo, because the profile for it is called "dev"
