### ISSUE TITLE
When running tests with --test-threads=1 there are failures

### ISSUE THREAD

**Issue by griff** [kornelski/cargo-deb#4]
When packaging this project for NixOS the tests are run on a machine with only one hardware thread and so it has the same effect as running `cargo test -- --test-threads=1` which means that all tests are run in series but this causes some tests to fail.

**Comment by kornelski** [comment]
Thanks for the report. It turns out tests used thread-local variables.

**Comment by griff** [comment]
Would it be possible to get a minor release with these fixes so they can be included in the comming 21.11 release of NixOS?
