### ISSUE TITLE
Use a folder with subdirectories in assets

### ISSUE THREAD

**Issue by jb-alvarado** [kornelski/cargo-deb#41]
Hello,
is there a way to copy recursive a folder with subdirectories in the assets? The Readme says that glob is supported, but `folder/*` or `folder/*.*` copies only the files inside the folder, but not directories and `folder/**` did not work.

**Comment by kornelski** [comment]
Currently it’s not possible. I agree it would be useful. Can you try adding it? The crate already uses globs.

**Comment by jb-alvarado** [comment]
I have try to integrate this, but failed on `data.rs -> archive_files(...)`, because here it wants files, not folders. 

But I also figure out, that I used the wrong glob pattern. In my project I don't exactly need empty folders (which would be nice, but not necessary). So when I use `folder/**/*` I get all files in any subdirectory.
