### ISSUE TITLE
mapping package release and project release

### ISSUE THREAD

**Issue by XopheD** [kornelski/cargo-deb#52]
Hi,

I’m using cargo-deb to automate the package generation and I would like that my project version remains consistent with the package one.

For example, if my project has version 1.2.3, I would generate a package as `myproject_1.2-3_amd64.deb`, i.e. I would like to use the last field of semver as the package release.

Is there an option to do that ? (at this moment, I should manually maintain the consistency between project version and cargo-deb configuration)

Regards, Ch.

**Comment by kornelski** [comment]
There's `--deb-version` and `--deb-revision`

**Comment by XopheD** [comment]
Ok, thanks, but I hope for something inside the manifest in order to alleviate the command line.
And I don’t understand why the patch number can’t be the revision number, it seems to be quite 'natural' for debian packages (or I suppose that I have not the correct meaning for this number).

Nevertheless, I agree that your suggestion does the job if I used that in conjunction with cargo-get (and as I have a workspace, I should also specify the main project root which contains the debian package configuration...):
```
cargo deb -p main --deb-version `cargo get --root=main version --major --minor --delimiter=.`-`cargo get --root=main version --patch`
```

So thanks again...
_(but if you can plan an evolution of the configuration in order to do that in the manifest, I'd like it ;))_
