### ISSUE TITLE
Question: How to handle dependency for static binary

### ISSUE THREAD

**Issue by manfredlotz** [kornelski/cargo-deb#6]
I have a Rust project where I build a static binary which I want to include into the deb package.

```
depends = "$auto"
```
yields
```
warning: Failed to find dependency specification. (no auto deps for....
```

Question: How would I code the depends statement correctly?

**Comment by kornelski** [comment]
Auto is only for executables. You need to list Debian deps manually.

**Comment by manfredlotz** [comment]
My wording was bad. Instead of `static binary` I should have said `static executable`. In this case `ldd` yields `not a dynamic executable`.

**Comment by kornelski** [comment]
I see. In that case you have no dependencies, so there's nothing to set.

**Comment by manfredlotz** [comment]
Ok. Now tried

```
depends = ''
```
which indeed works fine.

Thank you.
