### ISSUE TITLE
Consider supporting custom architectures

### ISSUE THREAD

**Issue by 2moe** [kornelski/cargo-deb#64]
https://github.com/kornelski/cargo-deb/blob/0a0598027d36a56c5357d5bb00e22f5c62c339d9/src/manifest.rs#L1179-L1197

In debian, there are mipsel and mips64el, but not mipsr6el and mips64r6el as above.

By the way, on some distributions, if you use dpkg to install deb packages, it will require the `musl-amd64` architecture instead of `amd64`.

I don't think relying on automated detection architecture will necessarily make everyone happy.

It will be even better, if we can configure `architectures` in `[package.metadata.deb]`.

**Comment by kornelski** [comment]
My philosophy with cargo deb is to work by default with just running `cargo deb`, so I'd prefer to fix or expand this list as necessary instead of adding manual configuration steps. There's a limited slow-changing list of architectures that both Rust and Debian support, so it shouldn't be too hard to keep up.

**Comment by 2moe** [comment]
In rust 1.71.0, the target triple [**loongarch64-unknown-linux-gnu** has been promoted to tiger2](https://github.com/rust-lang/rust/pull/110936/). 

However, different deb distributions correspond to different deb architectures for this target.

- In loongnix, it is loongarch64.
![loongarch64](https://github.com/kornelski/cargo-deb/assets/25324935/a31895fa-a44e-455b-88e0-3a8204073434)
- In debian-ports, it is loong64. 
![loong64](https://github.com/kornelski/cargo-deb/assets/25324935/7747727b-772c-4092-9fd3-ac28f304289d)

They are the same target, but they correspond to different deb architectures.

You might say, I don't have a loongarch CPU, why should I be concerned about this issue? 
All right. In fact, I don't have one either.
I'm just curious about how to solve this issue.

**Comment by kornelski** [comment]
What a mess with the naming. It looks like loong64 will eventually win, so I've picked that.
