### ISSUE TITLE
Running "update-rc.d defaults", "update-rc.d enable" and "service xxx start" on install?

### ISSUE THREAD

**Issue by fadedbee** [kornelski/cargo-deb#76]
Thanks for writing cargo-deb, my daemon packages already work with systemd-based OSs, such as Ubuntu and Debian.

I currently have /etc/init.d/xxx as a resource, and it is correctly installed with `dpkg -i`.

For sysv-init OSs, such as Devuan, I have to manually run `update-rc.d defaults`, `update-rc.d enable` and `service xxx start` after installing the package.

Does cargo-deb have any sysv-init support?

How can I automate these commands?

**Comment by ximon18** [comment]
Hi @fadedbee,

You can use the `maintainer-scripts` setting mentioned in the [README](https://github.com/kornelski/cargo-deb) for this.

Ximon
