### ISSUE TITLE
path of assets is not relative with --manifest-path

### ISSUE THREAD

**Issue by Cyrix126** [kornelski/cargo-deb#77]
Hi,

When using the "assets" option, the path is relative to the workspace, as expected.

But when the cargo-deb is ran with the option --manifest-path, paths specified in assets are relative to where the cargo-deb command is running instead of the workspace directory as --manifest-path of cargo build is doing.

**Comment by kornelski** [comment]
I can't reproduce it. The `example` project in the repo includes all the assets regardless of current dir.
