### ISSUE TITLE
`cargo test` failed on specific target

### ISSUE THREAD

**Issue by kimw** [kornelski/cargo-deb#8]
Since the `cmd_path` was hard coded as `"target/debug/cargo-deb"` in [tests/command.rs:161:5](https://github.com/kornelski/cargo-deb/blob/1b1d55ea1c2a201953cb3ebb2e1e14af1d091d2e/tests/command.rs#L10), any `cargo test` commands with specific target will fail, like `cargo test --target=x86_64-unknown-linux-gnu` or even `cargo test --release`.

---
- The `cmd_path` for `cargo test --release` should be `"target/release/cargo-deb"`.
- The `cmd_path` for `cargo test --target=x86_64-unknown-linux-gnu` should be `"target/x86_64_unknown-linux-gnu/debug/cargo-deb"`.

**Comment by kornelski** [comment]
I think this is fixed in 7b495087365d58a0cdfcd0e96994f98121e849cd
