### ISSUE TITLE
Running inside a container 

### ISSUE THREAD

**Issue by Ludea** [kornelski/cargo-deb#81]
I get `/root/.cargo/bin/cargo-deb: 1: Syntax error: word unexpected (expecting ")")` when using cargo-deb into a docker container.

I run `RUN cargo deb -p mysubcrate --target aarch64-unknown-linux-musl --no-build `. 
Same command works outside a container.

**Comment by kornelski** [comment]
This isn't how cargo-deb reports errors, so the error is coming from something else in your container, scripts, etc.

**Comment by Ludea** [comment]
My dockerfile
```
FROM messense/rust-musl-cross:aarch64-musl as cli
RUN sudo apt update
RUN sudo apt install -y protobuf-compiler
RUN cargo install cargo-deb
COPY . .
RUN cargo build --release --verbose
RUN cargo deb -p myfirstapp--target aarch64-unknown-linux-musl --no-build
RUN cargo deb -p mysecondapp --target aarch64-unknown-linux-musl --no-build
```

**Comment by Ludea** [comment]
Issue is not from cargo-deb

**Comment by kornelski** [comment]
What is "rgo"? Why is it running it in a new bash process, when others were not?

**Comment by kornelski** [comment]
I'm not providing support for GitHub actions. This is not cargo-deb problem. I can't solve it by changing cargo-deb.
