### ISSUE TITLE
`cargo deb` looks for target-specific configuration in target directory

### ISSUE THREAD

**Issue by domenicquirl** [kornelski/cargo-deb#84]
Hi, `cargo deb` doesn't seem to pick up a target-specific `strip` command if I set `$CARGO_TARGET_DIR` to a non-local folder (such as `/target` or whatever). I'd expect this to not influence loading a project's config, as `cargo` loads from the project directory (and up) or `$CARGO_HOME`, not `$CARGO_TARGET_DIR`, and it picks up config values like `alias`es just fine with this setup.

I think what might be happening is that `Config::cargo_config` [passes `self.target_dir`](https://github.com/kornelski/cargo-deb/blob/d773eb3430ef00973435ac4700ca10dc68dcc6c6/src/manifest.rs#L853) to `CargoConfig::new`, which expects a `project_path` instead.

It also seems a little inconsistent to read `$HOME` from the environment to check a user-wide configuration, but not `$CARGO_HOME` (the [Cargo Book](https://doc.rust-lang.org/cargo/reference/config.html#hierarchical-structure) lists `$CARGO_HOME/config.toml` as the global configuration directory, which the current behaviour matches for the default cargo home directory, I assume you already knew this). At least, that makes it quite annoying to work around this, because I have to _actually_ put the config inside the target directory (the build itelf is running inside a Docker container).

**Comment by domenicquirl** [comment]
While this is an issue, I also want to say that `cargo-deb` generally handles the setup very well otherwise. Including some very nice things like automatically resolving the path of `assets` that are targets - that was very welcome, so thanks for that!

**Comment by kornelski** [comment]
You're right that target dir shouldn't be used for config, and that conflated it with manifest dir. Can you make a PR?

**Comment by domenicquirl** [comment]
Opened #85 with a fix. It includes looking into `CARGO_HOME` as well, but you can let me know how you'd like to proceed there.

**Comment by kornelski** [comment]
Thank you
