### ISSUE TITLE
`cargo test` failed on Debian Buster

### ISSUE THREAD

**Issue by kimw** [kornelski/cargo-deb#9]
The `cargo test` works fine on Debian Bullseye, but not on Buster. The test reports:

```
...
test manifest::tests::add_systemd_assets_with_no_config_does_nothing ... ok
test manifest::tests::add_systemd_assets_with_config_adds_unit_assets ... ok
test dependencies::resolve_test ... FAILED

failures:

---- dependencies::resolve_test stdout ----
thread 'dependencies::resolve_test' panicked at 'assertion failed: !deps.iter().any(|d| d.starts_with(\"libgcc\"))', src/dependencies.rs:53:5


failures:
    dependencies::resolve_test

test result: FAILED. 108 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.02s

error: test failed, to rerun pass '--lib'
```

**Comment by kimw** [comment]
The binary build on Bullseye (which the test works fine) depends on,

    ["libc6 (>= 2.29)", "liblzma5 (>= 5.1.1alpha+20110809)"]

The binary build on Buster (which the test DO NOT work) depends on,
 
    ["libc6 (>= 2.18)", "libgcc1 (>= 1:4.2)", "liblzma5 (>= 5.1.1alpha+20110809)"]

The `libgcc1 (>= 1:4.2)` breaks the test.

**Comment by stappersg** [comment]
please consider to close this issue @kimw
