### ISSUE TITLE
Support switching between xz and gzip formats at runtime

### ISSUE THREAD

**Issue by scootermon** [kornelski/cargo-deb#96]
My use case for this is an embedded linux system that doesn't support LZMA compression.
Right now this can be achieved by building cargo-deb with default features disabled, but this also removes the option of using LZMA for systems that support it.

I would like to have an option akin to [fpm](https://github.com/jordansissel/fpm)'s [--deb-compression](https://fpm.readthedocs.io/en/latest/packages/deb.html?highlight=--deb-compression#deb-specific-command-line-flags) flag that allows me to explicitly select the compression when building the package.

I'm happy to contribute this feature, but I would like to get some guidance on the preferred approach.
The way I see it, this should be a command line option, but I'm also fine with having it as a field in the cargo.metadata.deb config.

**Comment by kornelski** [comment]
Yes, having a command line option for this is a good idea.
